---
- name: Backup Arista EOS Configurations
  hosts: all  # AWX will limit to selected inventory group
  gather_facts: no
  
  vars:
    backup_dir: "{{ playbook_dir }}/../configs/backup"
  
  tasks:
    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Backup running configuration
      arista.eos.eos_command:
        commands:
          - show running-config
      register: config_output

    - name: Save configuration to file
      ansible.builtin.copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"
      delegate_to: localhost

    - name: Display backup location
      ansible.builtin.debug:
        msg: "Configuration backed up to {{ backup_dir }}/{{ inventory_hostname }}_{{ ansible_date_time.date }}.cfg"