---
- name: Deploy Generated Configurations to Arista Devices
  hosts: all
  gather_facts: no
  
  vars:
    config_dir: "{{ playbook_dir }}/../configs/generated"
    
  tasks:
    - name: Check if generated config exists
      ansible.builtin.stat:
        path: "{{ config_dir }}/{{ inventory_hostname }}.cfg"
      delegate_to: localhost
      register: config_file

    - name: Fail if config doesn't exist
      ansible.builtin.fail:
        msg: "Configuration file not found. Run generate_configs.yml first."
      when: not config_file.stat.exists

    - name: Display configuration preview
      ansible.builtin.debug:
        msg: "Deploying configuration to {{ inventory_hostname }}"

    - name: Deploy configuration (config mode)
      arista.eos.eos_config:
        src: "{{ config_dir }}/{{ inventory_hostname }}.cfg"
        replace: config
        save_when: modified
      register: config_result
      # Add check mode support for AWX
      check_mode: "{{ ansible_check_mode | default(false) }}"

    - name: Display deployment results
      ansible.builtin.debug:
        msg: "Configuration {{ 'would be' if ansible_check_mode else 'was' }} deployed to {{ inventory_hostname }}"
      when: config_result.changed